branches:
  only:
    - master

install:
  - make get-deps
  
compiler:
  - gcc
build_script:
  - qmake main.pro
  - mingw32-make
after_build:
  - windeployqt release/main.exe
  - cmd: cp LICENSE release/LICENSE.txt"
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\YOUR-APP-*.exe
  - path: release
    type: zip
